export const CAMPAIGN_PLAN_TYPE_SCREEN_OWNER = "ScreenOwnerCampaign";

export const CREATE_CAMPAIGN_FOR_SCREEN_OWNER_REQUEST =
  "CREATE_CAMPAIGN_FOR_SCREEN_OWNER_REQUEST";
export const CREATE_CAMPAIGN_FOR_SCREEN_OWNER_SUCCESS =
  "CREATE_CAMPAIGN_FOR_SCREEN_OWNER_SUCCESS";
export const CREATE_CAMPAIGN_FOR_SCREEN_OWNER_FAIL =
  "CREATE_CAMPAIGN_FOR_SCREEN_OWNER_FAIL";
export const CREATE_CAMPAIGN_FOR_SCREEN_OWNER_RESET =
  "CREATE_CAMPAIGN_FOR_SCREEN_OWNER_RESET";

export const EDIT_CAMPAIGN_FOR_SCREEN_OWNER_REQUEST =
  "EDIT_CAMPAIGN_FOR_SCREEN_OWNER_REQUEST";
export const EDIT_CAMPAIGN_FOR_SCREEN_OWNER_SUCCESS =
  "EDIT_CAMPAIGN_FOR_SCREEN_OWNER_SUCCESS";
export const EDIT_CAMPAIGN_FOR_SCREEN_OWNER_FAIL =
  "EDIT_CAMPAIGN_FOR_SCREEN_OWNER_FAIL";
export const EDIT_CAMPAIGN_FOR_SCREEN_OWNER_RESET =
  "EDIT_CAMPAIGN_FOR_SCREEN_OWNER_RESET";

export const GET_SCREENS_CAMPAIGN_CREATIONS_FOR_SCREEN_OWNER_REQUEST =
  "GET_SCREENS_CAMPAIGN_CREATIONS_FOR_SCREEN_OWNER_REQUEST";
export const GET_SCREENS_CAMPAIGN_CREATIONS_FOR_SCREEN_OWNER_SUCCESS =
  "GET_SCREENS_CAMPAIGN_CREATIONS_FOR_SCREEN_OWNER_SUCCESS";
export const GET_SCREENS_CAMPAIGN_CREATIONS_FOR_SCREEN_OWNER_FAIL =
  "GET_SCREENS_CAMPAIGN_CREATIONS_FOR_SCREEN_OWNER_FAIL";

export const GET_SCREEN_DATA_UPLOAD_CREATIVE_REQUEST =
  "GET_SCREEN_DATA_UPLOAD_CREATIVE_REQUEST";
export const GET_SCREEN_DATA_UPLOAD_CREATIVE_SUCCESS =
  "GET_SCREEN_DATA_UPLOAD_CREATIVE_SUCCESS";
export const GET_SCREEN_DATA_UPLOAD_CREATIVE_FAIL =
  "GET_SCREEN_DATA_UPLOAD_CREATIVE_FAIL";

export const GET_ALL_CAMPAIGNS_DATA_REQUEST = "GET_ALL_CAMPAIGNS_DATA_REQUEST";
export const GET_ALL_CAMPAIGNS_DATA_SUCCESS = "GET_ALL_CAMPAIGNS_DATA_SUCCESS";
export const GET_ALL_CAMPAIGNS_DATA_FAIL = "GET_ALL_CAMPAIGNS_DATA_FAIL";

export const GET_CAMPAIGN_DATA_REQUEST = "GET_CAMPAIGN_DATA_REQUEST";
export const GET_CAMPAIGN_DATA_SUCCESS = "GET_CAMPAIGN_DATA_SUCCESS";
export const GET_CAMPAIGN_DATA_FAIL = "GET_CAMPAIGN_DATA_FAIL";

export const GET_FULL_CAMPAIGN_DATA_REQUEST = "GET_FULL_CAMPAIGN_DATA_REQUEST";
export const GET_FULL_CAMPAIGN_DATA_SUCCESS = "GET_FULL_CAMPAIGN_DATA_SUCCESS";
export const GET_FULL_CAMPAIGN_DATA_FAIL = "GET_FULL_CAMPAIGN_DATA_FAIL";

export const GET_CAMPAIGNCREATED_SCREENS_DATA_REQUEST =
  "GET_CAMPAIGNCREATED_SCREENS_DATA_REQUEST";
export const GET_CAMPAIGNCREATED_SCREENS_DATA_SUCCESS =
  "GET_CAMPAIGNCREATED_SCREENS_DATA_SUCCESS";
export const GET_CAMPAIGNCREATED_SCREENS_DATA_FAIL =
  "GET_CAMPAIGNCREATED_SCREENS_DATA_FAIL";

export const CAMPAIGN_STATUS_CHANGE_REQUEST = "CAMPAIGN_STATUS_CHANGE_REQUEST";
export const CAMPAIGN_STATUS_CHANGE_SUCCESS = "CAMPAIGN_STATUS_CHANGE_SUCCESS";
export const CAMPAIGN_STATUS_CHANGE_FAIL = "CAMPAIGN_STATUS_CHANGE_FAIL";
export const CAMPAIGN_STATUS_CHANGE_RESET = "CAMPAIGN_STATUS_CHANGE_RESET";

export const EDIT_ALL_SUB_CAMPAIGNS_REQUEST = "EDIT_ALL_SUB_CAMPAIGNS_REQUEST";
export const EDIT_ALL_SUB_CAMPAIGNS_SUCCESS = "EDIT_ALL_SUB_CAMPAIGNS_SUCCESS";
export const EDIT_ALL_SUB_CAMPAIGNS_FAIL = "EDIT_ALL_SUB_CAMPAIGNS_FAIL";
export const EDIT_ALL_SUB_CAMPAIGNS_RESET = "EDIT_ALL_SUB_CAMPAIGNS_RESET";

// status constant

export const CAMPAIGN_STATUS_PENDING = "Pending"; // plea not accepted
export const CAMPAIGN_STATUS_ACTIVE = "Active"; // plea accepted || direct created campaign by screen owner || after getting access from screen owner
export const CAMPAIGN_STATUS_DELETED = "Deleted"; // deleetd by Ally or brand || enddate >= current date
export const CAMPAIGN_STATUS_PAUSE = "Pause"; // pause by screen owner
export const CAMPAIGN_STATUS_REJECTED = "Rejected"; // pause by screen owner
export const CAMPAIGN_STATUS_COMPLETED = "Completed"; // when campaign.remainingSlots  = 0
export const CAMPAIGN_STATUS_HOLD = "Hold";

export const PENDING = "pending";
export const ACCEPTED = "accepted";
export const REJECTED = "rejected";
export const BUDGET = "budget";
export const FINAL = "final";
export const SCREEN = "screen";
export const PRIMARY_CAMPAIGN_MANAGER = "PrimaryCampaignManager";
export const SECONDARY_CAMPAIGN_MANAGER = "SecondaryCampaignManager";
export const PRIMARY_SCREEN_OWNER = "PrimaryScreenOwner";
export const CAMPAIGN_STATUS_PLEA_REQUEST_BUDGET_SENT = "PleaRequestBudgetSent";
export const CAMPAIGN_STATUS_PLEA_REQUEST_BUDGET_ACCEPTED =
  "PleaRequestBudgetAccepted";
export const CAMPAIGN_STATUS_PLEA_REQUEST_BUDGET_REJECTED =
  "PleaRequestBudgetRejected";
export const CAMPAIGN_STATUS_PLEA_REQUEST_SCREEN_APPROVAL_SENT =
  "PleaRequestScreenApprovalSent";
export const CAMPAIGN_STATUS_PLEA_REQUEST_SCREEN_APPROVAL_ACCEPTED =
  "PleaRequestScreenApprovalAccepted";
export const CAMPAIGN_STATUS_PLEA_REQUEST_SCREEN_APPROVAL_REJECTED =
  "PleaRequestScreenApprovalRejected";
export const CAMPAIGN_STATUS_PLEA_REQUEST_FINAL_APPROVAL_SENT =
  "PleaRequestFinalApprovalSent";
export const CAMPAIGN_STATUS_PLEA_REQUEST_FINAL_APPROVAL_ACCEPTED =
  "PleaRequestFinalApprovalAccepted";
export const CAMPAIGN_STATUS_PLEA_REQUEST_FINAL_APPROVAL_REJECTED =
  "PleaRequestFinalApprovalRejected";

export const BUDGET_PLEA = "BudgetPlea";
export const SCREEN_PLEA = "ScreenPlea";
export const FINAL_PLEA = "FinalPlea";

// Logs

export const GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_REQUEST =
  "GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_REQUEST";
export const GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_SUCCESS =
  "GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_SUCCESS";
export const GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_FAIL =
  "GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_FAIL";
export const GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_RESET =
  "GET_CAMPAIGN_LOGS_BY_CAMPAIGN_ID_RESET";
