// List Coupons
export const GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_REQUEST =
  "GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_REQUEST";
export const GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_SUCCESS =
  "GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_SUCCESS";
export const GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_FAIL =
  "GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_FAIL";
export const GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_RESET =
  "GET_ACTIVE_CAMPAIGN_LIST_FOR_MONITORING_RESET";

export const GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_REQUEST =
  "GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_REQUEST";
export const GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_SUCCESS =
  "GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_SUCCESS";
export const GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_FAIL =
  "GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_FAIL";
export const GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_RESET =
  "GET_ACTIVE_CAMPAIGN_LIST_SCREEN_WISE_FOR_MONITORING_RESET";

export const GET_CAMPAIGN_MONITORING_DATA_REQUEST =
  "GET_CAMPAIGN_MONITORING_DATA_REQUEST";
export const GET_CAMPAIGN_MONITORING_DATA_SUCCESS =
  "GET_CAMPAIGN_MONITORING_DATA_SUCCESS";
export const GET_CAMPAIGN_MONITORING_DATA_FAIL =
  "GET_CAMPAIGN_MONITORING_DATA_FAIL";
export const GET_CAMPAIGN_MONITORING_DATA_RESET =
  "GET_CAMPAIGN_MONITORING_DATA_RESET";

export const ADD_CAMPAIGN_MONITORING_DATA_REQUEST =
  "ADD_CAMPAIGN_MONITORING_DATA_REQUEST";
export const ADD_CAMPAIGN_MONITORING_DATA_SUCCESS =
  "ADD_CAMPAIGN_MONITORING_DATA_SUCCESS";
export const ADD_CAMPAIGN_MONITORING_DATA_FAIL =
  "ADD_CAMPAIGN_MONITORING_DATA_FAIL";
export const ADD_CAMPAIGN_MONITORING_DATA_RESET =
  "ADD_CAMPAIGN_MONITORING_DATA_RESET";
