export const GET_ALL_SCREENS_DATA_REQUEST = "GET_ALL_SCREENS_DATA_REQUEST";
export const GET_ALL_SCREENS_DATA_SUCCESS = "GET_ALL_SCREENS_DATA_SUCCESS";
export const GET_ALL_SCREENS_DATA_FAIL = "GET_ALL_SCREENS_DATA_FAIL";

export const GET_SCREEN_DATA_REQUEST = "GET_SCREEN_DATA_REQUEST";
export const GET_SCREEN_DATA_SUCCESS = "GET_SCREEN_DATA_SUCCESS";
export const GET_SCREEN_DATA_FAIL = "GET_SCREEN_DATA_FAIL";

export const GET_SCREEN_CAMPAIGNS_DATA_REQUEST = "GET_SCREEN_CAMPAIGNS_DATA_REQUEST";
export const GET_SCREEN_CAMPAIGNS_DATA_SUCCESS = "GET_SCREEN_CAMPAIGNS_DATA_SUCCESS";
export const GET_SCREEN_CAMPAIGNS_DATA_FAIL = "GET_SCREEN_CAMPAIGNS_DATA_FAIL";

export const SET_CAMPAIGNS_LOOP_FOR_SCREEN_REQUEST = "SET_CAMPAIGNS_LOOP_FOR_SCREEN_REQUEST";
export const SET_CAMPAIGNS_LOOP_FOR_SCREEN_SUCCESS = "SET_CAMPAIGNS_LOOP_FOR_SCREEN_SUCCESS";
export const SET_CAMPAIGNS_LOOP_FOR_SCREEN_FAIL = "SET_CAMPAIGNS_LOOP_FOR_SCREEN_FAIL";
export const SET_CAMPAIGNS_LOOP_FOR_SCREEN_RESET = "SET_CAMPAIGNS_LOOP_FOR_SCREEN_RESET";

export const EDIT_CAMPAIGN_CREATIVE_END_DATE_REQUEST = "EDIT_CAMPAIGN_CREATIVE_END_DATE_REQUEST";
export const EDIT_CAMPAIGN_CREATIVE_END_DATE_SUCCESS = "EDIT_CAMPAIGN_CREATIVE_END_DATE_SUCCESS";
export const EDIT_CAMPAIGN_CREATIVE_END_DATE_FAIL = "EDIT_CAMPAIGN_CREATIVE_END_DATE_FAIL";
export const EDIT_CAMPAIGN_CREATIVE_END_DATE_RESET = "EDIT_CAMPAIGN_CREATIVE_END_DATE_RESET";

export const SCREEN_CAMPAIGN_MONITORING_REQUEST = "SCREEN_CAMPAIGN_MONITORING_REQUEST";
export const SCREEN_CAMPAIGN_MONITORING__SUCCESS = "SCREEN_CAMPAIGN_MONITORING_SUCCESS";
export const SCREEN_CAMPAIGN_MONITORING__FAIL = "SCREEN_CAMPAIGN_MONITORING_FAIL";
export const SCREEN_CAMPAIGN_MONITORING__RESET = "SCREEN_CAMPAIGN_MONITORING_RESET";
