export const GET_ALL_SCREENS_DATA_REQUEST = "GET_ALL_SCREENS_DATA_REQUEST";
export const GET_ALL_SCREENS_DATA_SUCCESS = "GET_ALL_SCREENS_DATA_SUCCESS";
export const GET_ALL_SCREENS_DATA_FAIL = "GET_ALL_SCREENS_DATA_FAIL";

export const GET_SCREEN_DATA_REQUEST = "GET_SCREEN_DATA_REQUEST";
export const GET_SCREEN_DATA_SUCCESS = "GET_SCREEN_DATA_SUCCESS";
export const GET_SCREEN_DATA_FAIL = "GET_SCREEN_DATA_FAIL";

export const GET_SCREEN_CAMPAIGNS_DATA_REQUEST = "GET_SCREEN_CAMPAIGNS_DATA_REQUEST";
export const GET_SCREEN_CAMPAIGNS_DATA_SUCCESS = "GET_SCREEN_CAMPAIGNS_DATA_SUCCESS";
export const GET_SCREEN_CAMPAIGNS_DATA_FAIL = "GET_SCREEN_CAMPAIGNS_DATA_FAIL";
